### ISSUE TITLE
Accidental additional newline

### ISSUE THREAD

**Issue by LuudJanssen** [incentro-dc/remark-github-admonitions-to-directives#2]
Somehow the plugin adds an additional newline to the admonitions between the title and the body.

Markdown:

```markdown
> [!WARNING]  
> Any derivation of these guidelines should be discussed with the team.
```

Result:

![image](https://github.com/incentro-dc/remark-github-admonitions-to-directives/assets/12209111/b11a5e3d-c252-4861-870c-def903500ed5)

**Comment by oott123** [comment]
I also met this. After some very deep debug, I realized that:

This is not a bug, it's caused by the example of the highlight, which posted by the github community at https://github.com/orgs/community/discussions/16925 , and is very confusing:

```
> [!WARNING]  
            ^ two spaces here
```

Comment here for others who needs.
