### ISSUE TITLE
Mismatch of GitHub flavored 'IMPORTANT' alert to docusaurus admonition

### ISSUE THREAD

**Issue by johnmcase** [incentro-dc/remark-github-admonitions-to-directives#6]
I think there is a mis-mapping of the mapping of the GitHub `IMPORTANT` alert.  It appears to be mapping to the `:::warning` docusaurus admonition.

Consider the following Markdown in a docusaurus site with the `remark-github-admonitions-to-directives` plugin installed:

``` md
> [!NOTE]
> This is a GH flavored `NOTE`

:::note
This is a Docusaurus Admonition `note`
:::

> [!TIP]
> This is a GH flavored `TIP`

:::tip
This is a Docusaurus Admonition `tip`
:::

> [!IMPORTANT]
> This is a GH flavored `IMPORTANT`

:::info
This is a Docusaurus Admonition `info`
:::

> [!WARNING]
> This is a GH flavored `WARNING`

:::warning
This is a Docusaurus Admonition `warning`
:::

> [!CAUTION]
> This is a GH flavored `CAUTION`

:::danger
This is a Docusaurus Admonition `danger`
:::
```

The above code produces the following output:

![image](https://github.com/user-attachments/assets/009b1081-0850-4d5f-93ab-8191f8aa07d3)

I believe it should map to the `:::info` admonition.

**Comment by LuudJanssen** [comment]
Hi @johnmcase, I think you're right.

My reasoning was that "important" sounds a lot more invasive than "info", so that's why I mapped it to a "warning". I think my reasoning was wrong, and it makes much more sense if all GitHub admonition types map 1:1.

**Comment by damianstasik** [comment]
@LuudJanssen would you accept a PR that would allow customizing the mapping? My use case doesn't involve Docusaurus so it would be great to have 1:1 mapping with GitHub's naming.

**Comment by LuudJanssen** [comment]
Hi @damianstasik, yes I would! Did you already think about what this would look like? Like in what form would you pass the mapping to the plugin?

**Comment by LuudJanssen** [comment]
@damianstasik, I don't know if you're still interested in this change, but I added an option to customize the mapping in #9.
